# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except ImportError:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class MSAUtils(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login',
            service_ver='release',
            async_job_check_time_ms=100, async_job_check_time_scale_percent=150, 
            async_job_check_max_time_ms=300000):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = service_ver
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc,
            async_job_check_time_ms=async_job_check_time_ms,
            async_job_check_time_scale_percent=async_job_check_time_scale_percent,
            async_job_check_max_time_ms=async_job_check_max_time_ms)

    def import_msa_file(self, params, context=None):
        """
        import_msa_file: import a MSA from FASTA
        :param params: instance of type "ImportMSAParams" -> structure:
           parameter "input_shock_id" of String, parameter "input_file_path"
           of String, parameter "input_staging_file_path" of String,
           parameter "msa_name" of String, parameter "description" of String,
           parameter "workspace_name" of String
        :returns: instance of type "ImportMSAOutput" (@optional report_name
           report_ref) -> structure: parameter "report_name" of String,
           parameter "report_ref" of type "obj_ref" (An X/Y/Z style reference
           @id ws), parameter "msa_obj_ref" of type "obj_ref" (An X/Y/Z style
           reference @id ws)
        """
        return self._client.run_job('MSAUtils.import_msa_file',
                                    [params], self._service_ver, context)

    def msa_to_fasta_file(self, params, context=None):
        """
        :param params: instance of type "MSAToFileParams" -> structure:
           parameter "msa_name" of String, parameter "workspace_name" of
           String
        :returns: instance of type "MSAFilesOutput" -> structure: parameter
           "file_path" of String
        """
        return self._client.run_job('MSAUtils.msa_to_fasta_file',
                                    [params], self._service_ver, context)

    def msa_to_clustal_file(self, params, context=None):
        """
        :param params: instance of type "MSAToFileParams" -> structure:
           parameter "msa_name" of String, parameter "workspace_name" of
           String
        :returns: instance of type "MSAFilesOutput" -> structure: parameter
           "file_path" of String
        """
        return self._client.run_job('MSAUtils.msa_to_clustal_file',
                                    [params], self._service_ver, context)

    def export_msa_as_fasta_file(self, params, context=None):
        """
        :param params: instance of type "ExportParams" -> structure:
           parameter "input_ref" of type "obj_ref" (An X/Y/Z style reference
           @id ws)
        :returns: instance of type "ExportOutput" -> structure: parameter
           "shock_id" of String
        """
        return self._client.run_job('MSAUtils.export_msa_as_fasta_file',
                                    [params], self._service_ver, context)

    def export_msa_as_clustal_file(self, params, context=None):
        """
        :param params: instance of type "ExportParams" -> structure:
           parameter "input_ref" of type "obj_ref" (An X/Y/Z style reference
           @id ws)
        :returns: instance of type "ExportOutput" -> structure: parameter
           "shock_id" of String
        """
        return self._client.run_job('MSAUtils.export_msa_as_clustal_file',
                                    [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.run_job('MSAUtils.status',
                                    [], self._service_ver, context)
